export const GET_APPLICATIONS_RESPONSE = 'GET_APPLICATIONS_RESPONSE';
export const GET_APPLICATION_RESPONSE = 'GET_APPLICATION_RESPONSE';
export const ADD_NEW_APPLICATION_RESPONSE = 'ADD_NEW_APPLICATION_RESPONSE';
export const UPDATE_EXISTING_APPLICATION_RESPONSE = 'UPDATE_EXISTING_APPLICATION_RESPONSE';
export const DELETE_APPLICATION_RESPONSE = 'DELETE_APPLICATION_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
